name: FastMCP Server Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libgsl-dev build-essential
        version: 1.0

    - name: Install Python dependencies
      run: pip install -r requirements_mcp.txt

    - name: Build seq2exp executable
      run: |
        cd src
        make clean && make
        cp seq2exp ../
        cd ..

    - name: Test MCP server tools registration
      run: python3 Tests/test_server_tools.py

    - name: Test MCP protocol communication
      run: python3 Tests/test_mcp_stdio.py

    - name: Test comprehensive MCP tool calls
      run: python3 Tests/comprehensive_test_mcp.py

    - name: Test FastMCP validation tool
      run: python3 Tests/test_validation_tool.py
